In [21]:
import tensorflow as tf
import PySimpleGUI as sg
import os


if tf.config.list_physical_devices('GPU'):
    print('GPU is available')
else:
    print('GPU is not available')



GPU is available


In [22]:
# # Define the PySimpleUI layout
# layout = [
#     [sg.Text('Select the directory containing the model checkpoint files')],
#     [sg.Input(key='-FOLDER-'), sg.FolderBrowse()],
#     [sg.Button('Load Model'), sg.Button('Cancel')]
# ]


# model = tf.keras.models.Sequential([
#                     # ... add layers to the model here ...
#                 ])

#                 # Load the checkpoint files
# checkpoint_dir = '/home/rifat/miniconda3/Bio_ClinicalBERT'
# checkpoint_path = os.path.join(checkpoint_dir, 'model.ckpt-150000')
# model_got = model.load_weights(checkpoint_path)


In [23]:
import pandas as pd 

data = pd.read_csv("/home/rifat/miniconda3/Bio_ClinicalBERT/data_tensor.csv")
data.head()

habits                                           symptoms  \
0    non-smoker                      fever, muscle aches, headache   
1    non-smoker                     runny nose, cough, sore throat   
2  chain-smoker  weight loss, jaundice, abdominal pain, loss of...   
3  chain-smoker  coughing up blood, chest pain, shortness of br...   
4    non-smoker                          fatigue, nausea, diarrhea   

   probability_of_cancer  
0                      0  
1                      0  
2                      1  
3                      1  
4                      0

In [24]:
train_data = data.sample(frac=0.8, random_state=42)
test_data = data.drop(train_data.index)
print(train_data)

          habits                                           symptoms  \
8     non-smoker                     headache, dizziness, confusion   
16    non-smoker       sudden vision loss, blurred vision, eye pain   
0     non-smoker                      fever, muscle aches, headache   
18    non-smoker               frequent fevers, infections, fatigue   
11  chain-smoker  yellowing of the skin and eyes, abdominal swel...   
9   chain-smoker     pain or pressure in the chest, nausea, fatigue   
13  chain-smoker         fatigue, weakness, unexplained weight loss   
1     non-smoker                     runny nose, cough, sore throat   
21  chain-smoker  swelling or lumps in the testicles, pain or di...   
5   chain-smoker  difficulty swallowing, hoarseness, persistent ...   
2   chain-smoker  weight loss, jaundice, abdominal pain, loss of...   
12    non-smoker                         itching, redness, swelling   
15  chain-smoker               bleeding from rectum, abdominal pain   
3   ch

In [25]:
from transformers import AutoTokenizer 
checkpoint_dir = '/home/rifat/miniconda3/Bio_ClinicalBERT'

file_path = checkpoint_dir

if os.path.exists(file_path):
    tokenizer = AutoTokenizer.from_pretrained(file_path)
    # use the tokenizer object for further processing
else:
    print("Error: specified file path does not exist.")


train_tokens = tokenizer.batch_encode_plus(
    train_data[['habits', 'symptoms']].values.tolist(),
    max_length=16,
    padding='max_length',
    truncation=True,
    return_token_type_ids=True,
    return_attention_mask=True,
    return_tensors='tf'
)
print(train_tokens)

{'input_ids': <tf.Tensor: shape=(19, 16), dtype=int32, numpy=
array([[  101,  1664,   118,  5427,  1197,   102, 16320,   117,  4267,
        15284,  1757,   117,  6406,   102,     0,     0],
       [  101,  1664,   118,  5427,  1197,   102,  4962,  4152,  2445,
          117, 20611,  4152,   117,  2552,  2489,   102],
       [  101,  1664,   118,  5427,  1197,   102, 10880,   117,  6484,
        12953,  1116,   117, 16320,   102,     0,     0],
       [  101,  1664,   118,  5427,  1197,   102,  6539, 10880,  1116,
          117, 16565,   117, 18418,   102,     0,     0],
       [  101,  4129,   118,  5427,  1197,   102,  3431,  1158,  1104,
         1103,  2241,  1105,  1257,   117, 24716,   102],
       [  101,  4129,   118,  5427,  1197,   102,  2489,  1137,  2997,
         1107,  1103,  2229,   117, 22882,   117,   102],
       [  101,  4129,   118,  5427,  1197,   102, 18418,   117, 11477,
          117, 25731,  1775, 18220,  1174,  2841,   102],
       [  101,  1664,   118,  5427,

In [26]:
test_tokens = tokenizer.batch_encode_plus(
    test_data[['habits', 'symptoms']].values.tolist(),
    max_length=16,
    padding='max_length',
    truncation=True,
    return_token_type_ids=True,
    return_attention_mask=True,
    return_tensors='tf'
)
print(test_tokens)

{'input_ids': <tf.Tensor: shape=(5, 16), dtype=int32, numpy=
array([[  101,  1664,   118,  5427,  1197,   102,   187, 10733,   117,
         1122,  7520,   117, 20085,   102,     0,     0],
       [  101,  4129,   118,  5427,  1197,   102,  2489,  1137, 19614,
         1107,  1103, 14701,   117,  2607,  1107,   102],
       [  101,  1664,   118,  5427,  1197,   102,  6539,   190,  9324,
         2116,   117,  7262,   190,  9324,  1916,   102],
       [  101,  1664,   118,  5427,  1197,   102,  1171,  2489,   117,
        18152,  1757,  1137, 11477,  1107,  2584,   102],
       [  101,  4129,   118,  5427,  1197,   102, 20085,  1137, 16401,
         1116,  1107,  1103,  2455,   117,  7262,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(5, 16), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1

In [27]:
# Convert the tokens to IDs
train_input_ids = train_tokens['input_ids']
test_input_ids = test_tokens['input_ids']

print(train_input_ids)
print(test_input_ids)

tf.Tensor(
[[  101  1664   118  5427  1197   102 16320   117  4267 15284  1757   117
   6406   102     0     0]
 [  101  1664   118  5427  1197   102  4962  4152  2445   117 20611  4152
    117  2552  2489   102]
 [  101  1664   118  5427  1197   102 10880   117  6484 12953  1116   117
  16320   102     0     0]
 [  101  1664   118  5427  1197   102  6539 10880  1116   117 16565   117
  18418   102     0     0]
 [  101  4129   118  5427  1197   102  3431  1158  1104  1103  2241  1105
   1257   117 24716   102]
 [  101  4129   118  5427  1197   102  2489  1137  2997  1107  1103  2229
    117 22882   117   102]
 [  101  4129   118  5427  1197   102 18418   117 11477   117 25731  1775
  18220  1174  2841   102]
 [  101  1664   118  5427  1197   102  1576  3382  3678   117 21810   117
  15939  2922   102     0]
 [  101  4129   118  5427  1197   102 20085  1137 16401  1116  1107  1103
   2774 26407   117   102]
 [  101  4129   118  5427  1197   102  7262 24841   117 23523  1757   117
  1597

In [28]:
train_attention_masks = train_tokens['attention_mask']
test_attention_masks = test_tokens['attention_mask']
print(train_attention_masks)
print(test_attention_masks)

tf.Tensor(
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]], shape=(19, 16), dtype=int32)
tf.Tensor(
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]], shape=(5, 16), dtype=int32)


In [29]:
# Create segment IDs
train_token_type_ids = train_tokens['token_type_ids']
test_token_type_ids = test_tokens['token_type_ids']
print(train_token_type_ids)
print(test_token_type_ids)

tf.Tensor(
[[0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]], shape=(19, 16), dtype=int32)
tf.Tensor(
[[0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]], shape=(5, 16), dtype=int32)


In [30]:
train_labels = tf.constant(train_data['probability_of_cancer'].values)
test_labels = tf.constant(test_data['probability_of_cancer'].values)
print(train_labels)
print(test_labels)


tf.Tensor([0 0 0 0 1 1 1 0 1 1 1 0 1 1 0 0 1 0 1], shape=(19,), dtype=int64)
tf.Tensor([0 1 0 0 1], shape=(5,), dtype=int64)


In [31]:
# Print the shapes of the input tensors
print('Train input IDs shape:', train_input_ids.shape)
print('Train attention masks shape:', train_attention_masks.shape)
print('Train token type IDs shape:', train_token_type_ids.shape)
print('Train labels shape:', train_labels.shape)

print('Test input IDs shape:', test_input_ids.shape)
print('Test attention masks shape:', test_attention_masks.shape)
print('Test token type IDs shape:', test_token_type_ids.shape)
print('Test labels shape:', test_labels.shape)

Train input IDs shape: (19, 16)
Train attention masks shape: (19, 16)
Train token type IDs shape: (19, 16)
Train labels shape: (19,)
Test input IDs shape: (5, 16)
Test attention masks shape: (5, 16)
Test token type IDs shape: (5, 16)
Test labels shape: (5,)


In [32]:
import numpy as np
from tensorflow.python.ops.numpy_ops import np_config
np_config.enable_numpy_behavior()


# Convert input features to float32
train_input_ids_train = train_input_ids.astype(np.float32)
train_attention_masks_train = train_attention_masks.astype(np.float32)
train_attention_type_train = train_token_type_ids.astype(np.float32)

# Convert output features to float32
test_input_ids_test = test_input_ids.astype(np.float32)
test_attention_masks_test = test_attention_masks.astype(np.float32)
test_token_type_ids_test = test_token_type_ids.astype(np.float32)


In [33]:
# Print the shapes of the input tensors
print('Train input IDs shape:', train_input_ids_train.shape)
print('Train attention masks shape:', train_attention_masks_train.shape)
print('Train token type IDs shape:', train_attention_type_train.shape)
print('Train labels shape:', train_labels.shape)

print('Test input IDs shape:', test_input_ids_test.shape)
print('Test attention masks shape:', test_attention_masks_test.shape)
print('Test token type IDs shape:', test_token_type_ids_test.shape)
print('Test labels shape:', test_labels.shape)

Train input IDs shape: (19, 16)
Train attention masks shape: (19, 16)
Train token type IDs shape: (19, 16)
Train labels shape: (19,)
Test input IDs shape: (5, 16)
Test attention masks shape: (5, 16)
Test token type IDs shape: (5, 16)
Test labels shape: (5,)


In [34]:
# Define the model architecture
model = tf.keras.models.Sequential([
    # ... add layers to the model here ...
])

# Create a Keras optimizer
optimizer = tf.keras.optimizers.Adam(learning_rate=2e-5, epsilon=1e-08)

# Compile the model
model.compile(
    optimizer=optimizer,
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), 
    metrics=[tf.keras.metrics.SparseCategoricalAccuracy(name='accuracy')]
)


# Save the model weights and optimizer state
checkpoint_dir = '/home/rifat/miniconda3/Bio_ClinicalBERT'
checkpoint_prefix = os.path.join(checkpoint_dir, 'ckpt')
checkpoint = tf.train.Checkpoint(model=model, optimizer=optimizer)
checkpoint.save(checkpoint_prefix)



# Load the model weights and optimizer state from the checkpoint directory
checkpoint = tf.train.Checkpoint(model=model, optimizer=optimizer)
checkpoint.restore(tf.train.latest_checkpoint(checkpoint_dir))
# # Test the restored model
# test_loss, test_acc = model.evaluate([test_input_ids_test, test_attention_masks_test, test_token_type_ids_test], test_labels)
# print(f'Test Loss: {test_loss}, Test Accuracy: {test_acc}')


In [35]:
import tensorflow as tf





# Train the model
history = model.fit(
    [train_input_ids_train, train_attention_masks_train, train_attention_type_train], 
    train_labels, 
    epochs=100, 
    batch_size=16, 
    validation_data=([test_input_ids_test, test_attention_masks_test, test_token_type_ids_test], test_labels)
)







Epoch 1/100
2/2 [==============================] - 1s 213ms/step - loss: 20802.3086 - output_1_loss: 20796.1055 - output_2_loss: 2.7424 - output_3_loss: 3.4621 - output_1_accuracy: 0.0000e+00 - output_2_accuracy: 0.4737 - output_3_accuracy: 0.0000e+00 - val_loss: 15746.1748 - val_output_1_loss: 15739.9395 - val_output_2_loss: 2.7561 - val_output_3_loss: 3.4802 - val_output_1_accuracy: 0.0000e+00 - val_output_2_accuracy: 0.6000 - val_output_3_accuracy: 0.0000e+00
Epoch 2/100
2/2 [==============================] - 0s 49ms/step - loss: 20802.3086 - output_1_loss: 20796.1055 - output_2_loss: 2.7424 - output_3_loss: 3.4621 - output_1_accuracy: 0.0000e+00 - output_2_accuracy: 0.4737 - output_3_accuracy: 0.0000e+00 - val_loss: 15746.1748 - val_output_1_loss: 15739.9395 - val_output_2_loss: 2.7561 - val_output_3_loss: 3.4802 - val_output_1_accuracy: 0.0000e+00 - val_output_2_accuracy: 0.6000 - val_output_3_accuracy: 0.0000e+00
Epoch 3/100
2/2 [==============================] - 0s 52ms/step - l

In [36]:
# Evaluate the model on the test data
results = model.evaluate([test_input_ids_test, test_attention_masks_test, test_token_type_ids_test], test_labels)

print('Test loss:', results[0])
print('Test accuracy:', results[1])

1/1 [==============================] - 0s 30ms/step - loss: 15746.1748 - output_1_loss: 15739.9395 - output_2_loss: 2.7561 - output_3_loss: 3.4802 - output_1_accuracy: 0.0000e+00 - output_2_accuracy: 0.6000 - output_3_accuracy: 0.0000e+00
Test loss: 15746.1748046875
Test accuracy: 15739.939453125


In [37]:
test_data


habits                                           symptoms  \
6     non-smoker                            rash, itching, swelling   
7   chain-smoker  pain or discomfort in the abdomen, changes in ...   
10    non-smoker  frequent urination, difficulty urinating, bloo...   
14    non-smoker            back pain, numbness or weakness in legs   
19  chain-smoker  swelling or lumps in the neck, difficulty swal...   

    probability_of_cancer  
6                       0  
7                       1  
10                      0  
14                      0  
19                      1

In [38]:
model.predict([test_input_ids, test_attention_masks, test_token_type_ids])

1/1 [==============================] - 0s 50ms/step


(array([[  101,  1664,   118,  5427,  1197,   102,   187, 10733,   117,
          1122,  7520,   117, 20085,   102,     0,     0],
        [  101,  4129,   118,  5427,  1197,   102,  2489,  1137, 19614,
          1107,  1103, 14701,   117,  2607,  1107,   102],
        [  101,  1664,   118,  5427,  1197,   102,  6539,   190,  9324,
          2116,   117,  7262,   190,  9324,  1916,   102],
        [  101,  1664,   118,  5427,  1197,   102,  1171,  2489,   117,
         18152,  1757,  1137, 11477,  1107,  2584,   102],
        [  101,  4129,   118,  5427,  1197,   102, 20085,  1137, 16401,
          1116,  1107,  1103,  2455,   117,  7262,   102]], dtype=int32),
 array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32),
 array([[0, 0, 0, 0, 0, 0

In [39]:
logits = tf.constant([[  101,  1664,   118,  5427,  1197,   102,   187, 10733,   117,
          1122,  7520,   117, 20085,   102,     0,     0],
        [  101,  4129,   118,  5427,  1197,   102,  2489,  1137, 19614,
          1107,  1103, 14701,   117,  2607,  1107,   102],
        [  101,  1664,   118,  5427,  1197,   102,  6539,   190,  9324,
          2116,   117,  7262,   190,  9324,  1916,   102],
        [  101,  1664,   118,  5427,  1197,   102,  1171,  2489,   117,
         18152,  1757,  1137, 11477,  1107,   2584, 102],
        [  101,  4129,   118,  5427,  1197,   102, 20085,  1137, 16401,
          1116,  1107,  1103,  2455,   117,  7262,   102]])

# Cast logits to float32
logits_float = tf.cast(logits, tf.float32)

probabilities = tf.nn.softmax(logits_float, axis=1)

print(probabilities)


tf.Tensor(
[[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.5 0.  0.  0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]], shape=(5, 16), dtype=float32)


In [40]:
probs = tf.constant([
    [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
    [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
    [0., 0., 0., 0., 0., 0., 0., 0., 0.5, 0., 0., 0., 0., 0.5, 0., 0.],
    [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
    [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]
], dtype=tf.float32)

# Probabilities for the first input sample
class_0_prob = probs[0][0]
class_1_prob = probs[0][1]
class_2_prob = probs[0][2]
class_3_prob = probs[0][3]
class_4_prob = probs[0][4]

print('Probability for class 0:', class_0_prob)
print('Probability for class 1:', class_1_prob)
print('Probability for class 2:', class_2_prob)
print('Probability for class 3:', class_3_prob)
print('Probability for class 4:', class_4_prob)


Probability for class 0: tf.Tensor(0.0, shape=(), dtype=float32)
Probability for class 1: tf.Tensor(0.0, shape=(), dtype=float32)
Probability for class 2: tf.Tensor(0.0, shape=(), dtype=float32)
Probability for class 3: tf.Tensor(0.0, shape=(), dtype=float32)
Probability for class 4: tf.Tensor(0.0, shape=(), dtype=float32)


In [41]:
# Save the model to a directory
model.save('/home/rifat/miniconda3/Bio_ClinicalBERT/cance_gpu')
model.save('/home/rifat/miniconda3/Bio_ClinicalBERT')

INFO:tensorflow:Assets written to: /home/rifat/miniconda3/Bio_ClinicalBERT/cance_gpu/assets


INFO:tensorflow:Assets written to: /home/rifat/miniconda3/Bio_ClinicalBERT/cance_gpu/assets


INFO:tensorflow:Assets written to: /home/rifat/miniconda3/Bio_ClinicalBERT/assets


INFO:tensorflow:Assets written to: /home/rifat/miniconda3/Bio_ClinicalBERT/assets
